# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binary_search <- function(cards, dates) {
    .Call(`_RcppBinarySearch_binary_search`, cards, dates)
}

binary_search_reverse <- function(cards, dates) {
    .Call(`_RcppBinarySearch_binary_search_reverse`, cards, dates)
}

