// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// binary_search
CharacterVector binary_search(CharacterVector cards, CharacterVector dates);
RcppExport SEXP _RcppBinarySearch_binary_search(SEXP cardsSEXP, SEXP datesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cards(cardsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    rcpp_result_gen = Rcpp::wrap(binary_search(cards, dates));
    return rcpp_result_gen;
END_RCPP
}
// binary_search_reverse
CharacterVector binary_search_reverse(CharacterVector cards, CharacterVector dates);
RcppExport SEXP _RcppBinarySearch_binary_search_reverse(SEXP cardsSEXP, SEXP datesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cards(cardsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    rcpp_result_gen = Rcpp::wrap(binary_search_reverse(cards, dates));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppBinarySearch_binary_search", (DL_FUNC) &_RcppBinarySearch_binary_search, 2},
    {"_RcppBinarySearch_binary_search_reverse", (DL_FUNC) &_RcppBinarySearch_binary_search_reverse, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppBinarySearch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
